name: 'First Workflow'
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello World from H.O.M.E.R."
            - name: Multiline Commands
              run: |
                node -v
                npm  -v
